services:
  db:
    image: postgres
    container_name: postgres-catalog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MyStrong!Passw0rd
      POSTGRES_DB: catalog_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - catalog_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:

networks:
  catalog_network:
    driver: bridge